/* Generated by Cython 0.29.28 */

#ifndef __PYX_HAVE__libxfce4airhorn
#define __PYX_HAVE__libxfce4airhorn

#include "Python.h"

#ifndef __PYX_HAVE_API__libxfce4airhorn

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void init_plugin(XfcePanelPlugin *);

#endif /* !__PYX_HAVE_API__libxfce4airhorn */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initlibxfce4airhorn(void);
#else
PyMODINIT_FUNC PyInit_libxfce4airhorn(void);
#endif

#endif /* !__PYX_HAVE__libxfce4airhorn */
